# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_auto_20180610_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='waged',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
