# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_auto_20180617_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetype',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
