# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTypeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('wageMultiple', models.FloatField(default=1, max_length=4)),
                ('employeeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeTypes.EmployeeType')),
            ],
        ),
    ]
