# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-04 18:45
from __future__ import unicode_literals

import Common.Validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0002_auto_20180610_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[Common.Validators.validate_alpha_numeric])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.Company')),
            ],
        ),
    ]
