# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_jwt_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
