# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 12:42
from __future__ import unicode_literals

import Common.Validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=20000, validators=[Common.Validators.validate_alpha_numeric]),
        ),
    ]
